### ISSUE TITLE
FDEFN handling

### ISSUE THREAD

**Issue by Bike** [clasp-developers/cvm#1]
Global function references should be processed in such a way that a runtime can choose to do something more efficient than a full `fdefinition` call. Specifically, something like SBCL's fdefns or SICL's function cells must be supported. This entails compiler support, but also runtime support in that the runtime FDEFINITION instruction needs to do something simpler (e.g. load from a cell).

**Comment by karlosz** [comment]
Nothing needs to change on the VM instruction set side actually. It would probably be better to change the name to REF-FUNCTION-CELL n, but we just say that it grabs the function cell value from the nth constant and pushes it on the stack. Currently the object is a symbol, but it doesn't have to be: the compiler/dumper puts whatever object it wants there, like a more dedicated fdefn/cell object that admits more direct access than lookup of the function object through a symbol. The VM implementation changes of course accordingly.

**Comment by Bike** [comment]
that's pretty much exactly what i did in the branch, if i understand you correctly. just changed what the instruction does rather than adding a new instruction. i think i may have to add an instruction to the FASL loader to get a cell, but that's different from the VM instruction set

**Comment by karlosz** [comment]
Yeah new fasl op for fasloader sounds right.

**Comment by Bike** [comment]
done as of 0.11
